reviews:
    assess_linked_issues: false
    collapse_walkthrough: true
    high_level_summary: false
    review_status: false
    suggested_labels: false
    suggested_reviewers: false
    poem: false
    path_instructions:
    - path: '**/*.{php,js,ts,jsx,tsx}'
      instructions: |
        Don't trust that extension developers will follow the best practices, make sure the code:
        - Guards against unexpected inputs.
        - Sanitizes and validates any potentially dangerous inputs.
        - Is backwards compatible.
        - Is readable and intuitive.
        - Has unit or E2E tests where applicable.
        When making any changes to code that deletes or modifies orders/products/customer data, make sure that there are
        sufficient checks in place to prevent accidental data loss. As an example, if deleting a draft order, check that
        the order status is indeed `draft` or `checkout-draft`. Also think about whether race conditions could occur and
        delete orders that don't belong to the current customer. When in doubt, ask for clarification in the PR comments.
